#!/usr/bin/env python3

import sys
from admin_api import *
    
if len(sys.argv) != 3:
    print("Usage: change-password <email> <password>")
    sys.exit(1)

change_password(sys.argv[1], sys.argv[2])

