#!/usr/bin/env python3

import sys
from admin_api import *
    
if len(sys.argv) != 5:
    print("Usage: create-user <email> <first> <last> <password>")
    sys.exit(1)

create_user(sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4])

